site_name: Security and Privacy Laboratory

theme:
  name: material
  language: ja
  palette:
    scheme: default
    primary: white
    accent: deep orange
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
  icon:
    logo: material/shield-lock
  font: false
  extra:
    homepage: https://www.intrusion-detection.org
extra_css:
  - stylesheets/extra.css    
copyright: Copyright &copy; 2025 - 2026 Security and Privacy Laboratory & Akira Yamada. All rights reserved.
extra:
  analytics:
    provider: google
    property: G-H15GG1H14V
nav:
  - Home: index.md
  - People: people.md
  - Research: research.md
  - Publications: publications.md
  - Student Projects: projects.md
  - Lectures: lectures.md
  - Contact: contact.md
